const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Plugins.Camera3D,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.LOS,
		C3.Behaviors.Timer,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Behaviors.bound,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Acts.LockKeyboard,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Sprite: 0},
	{Suporte: 0},
	{Solid: 0},
	{Flash: 0},
	{Baú: 0},
	{Platform: 0},
	{Caixa: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Platform2: 0},
	{Platform3: 0},
	{Platform4: 0},
	{Platform5: 0},
	{Caixaa: 0},
	{Sprite4: 0},
	{"3DCamera": 0},
	{Porta: 0},
	{Tilemap2: 0},
	{Chave: 0},
	{Bomba: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Sprite5: 0},
	{SensorSólido: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Tilemap3: 0},
	{Sprite6: 0},
	{Direcao: 0},
	{Porco_Patrulheiro: 0},
	{Sensor_Patrulheiro_Direita: 0},
	{Sensor_Patrulheiro_Esquerda: 0},
	{cavernaTilemap: 0},
	{fundocaverna: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Bullet: 0},
	{Flecha: 0},
	{Mosaico: 0},
	{fundoilha: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Mosaico2: 0},
	{ilhatilemap: 0},
	{Sprite7: 0},
	{barril: 0},
	{Sólido: 0},
	{caixailha: 0},
	{bau: 0},
	{baucommuitodinheiro: 0},
	{bandeirapirata: 0},
	{concha: 0},
	{esqueletoParado: 0},
	{Vida: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{CampoDeVisão: 0},
	{Cronômetro: 0},
	{esqueleto: 0},
	{Ataque: 0},
	{bruxão: 0},
	{capitão: 0},
	{caranguejo: 0},
	{patrick: 0},
	{Vivo: 0},
	{Porco_Canhao: 0},
	{Canhao: 0},
	{DestroyOutside: 0},
	{Rotate: 0},
	{Bala: 0},
	{sensor_canhao: 0},
	{RestritoAoLayout: 0},
	{Vida_HUD: 0},
	{Itens_HUD: 0},
	{Sprite8: 0},
	{Fundo_Preto: 0},
	{Jogador_Dialogo: 0},
	{Chao_Caverna: 0},
	{Chefao: 0},
	{Plano_Preto: 0},
	{SpriteFont: 0},
	{Municao: 0},
	{SpriteFont2: 0},
	{Audio: 0},
	{SpriteFont3: 0},
	{tempo: 0},
	{SpriteFont4: 0},
	{ponto: 0},
	{pegarFlecha: 0},
	{flechaRecarga: 0},
	{danoEspinho: 0},
	{munição_gruta: 0},
	{dano: 0},
	{sensorfeitico: 0},
	{Menu: 0},
	{BotaoFase1: 0},
	{BotaoFase2: 0},
	{BotaoFase3: 0},
	{vida_jogador: 0},
	{Tempo: 0},
	{Pontos: 0},
	{Vida_Esqueleto: 0},
	{Municao4: 0},
	{vida_jogador2: 0},
	{Municao2: 0},
	{Tempo2: 0},
	{Pontos2: 0},
	{vida_jogador3: 0},
	{Municao3: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Baú: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Caixaa: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Porta: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	SensorSólido: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Porco_Patrulheiro: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Direita: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Esquerda: class extends self.ISpriteInstance {},
	cavernaTilemap: class extends self.ITilemapInstance {},
	fundocaverna: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Flecha: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	fundoilha: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	ilhatilemap: class extends self.ITilemapInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	barril: class extends self.ISpriteInstance {},
	caixailha: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	baucommuitodinheiro: class extends self.ISpriteInstance {},
	bandeirapirata: class extends self.ISpriteInstance {},
	concha: class extends self.ISpriteInstance {},
	esqueletoParado: class extends self.ISpriteInstance {},
	esqueleto: class extends self.ISpriteInstance {},
	bruxão: class extends self.ISpriteInstance {},
	capitão: class extends self.ISpriteInstance {},
	caranguejo: class extends self.ISpriteInstance {},
	patrick: class extends self.ISpriteInstance {},
	Porco_Canhao: class extends self.ISpriteInstance {},
	Canhao: class extends self.ISpriteInstance {},
	Bala: class extends self.ISpriteInstance {},
	sensor_canhao: class extends self.ISpriteInstance {},
	Vida_HUD: class extends self.ISpriteInstance {},
	Itens_HUD: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Fundo_Preto: class extends self.ISpriteInstance {},
	Jogador_Dialogo: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	Bomba: class extends self.ISpriteInstance {},
	Chao_Caverna: class extends self.ISpriteInstance {},
	Chefao: class extends self.ISpriteInstance {},
	Plano_Preto: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Municao: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	tempo: class extends self.ISpriteFontInstance {},
	SpriteFont4: class extends self.ISpriteFontInstance {},
	ponto: class extends self.ISpriteFontInstance {},
	pegarFlecha: class extends self.ISpriteInstance {},
	flechaRecarga: class extends self.ISpriteInstance {},
	danoEspinho: class extends self.ISpriteInstance {},
	munição_gruta: class extends self.ISpriteInstance {},
	sensorfeitico: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	BotaoFase1: class extends self.ISpriteInstance {},
	BotaoFase2: class extends self.ISpriteInstance {},
	BotaoFase3: class extends self.ISpriteInstance {}
}